[tool.briefcase]
project_name = "NMEA Logger"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/nmealogger"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.nmealogger]
formal_name = "NMEA Logger"
description = "My first application"
icon = "src/nmealogger/resources/helloworld"
sources = ['src/nmealogger']
requires = [
]


[tool.briefcase.app.nmealogger.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.nmealogger.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.nmealogger.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.nmealogger.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.nmealogger.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
