[package]
name = "udp"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap-parser = "0.14.0"
etherparse = "0.12.0"
chrono = "0.4.22"
clap = { version = "4.0.8", features = ["derive"] }

[[bin]]
name = "udp"
path = "udp.rs"
