[package]
name = "udp"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap-parser = "0.14.0"
etherparse = "0.10.1"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive"] }

[[bin]]
name = "udp"
path = "udp.rs"
